WebVotingSystem/Controllers/CandidatosController.cs
using Microsoft.AspNetCore.Mvc;
using WebVotingSystem.Models;
using WebVotingSystem.DataAccess.Repositorio.IRepositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace WebVotingSystem.Controllers
{
    public class CandidatosController : Controller
    {
        public CandidatosController(IControlador controlador, IWebHostEnvironment webHostEnvironment)
        {
            _controlador = controlador;
            _webHostEnvironment = webHostEnvironment;
        }

        readonly IControlador _controlador;
        readonly IWebHostEnvironment _webHostEnvironment;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null)
            {
                // Create
                return View(new Candidato());
            }
            else
            {
                // Edit
                Candidato candididato = _controlador.Candidato.Buscar(id.GetValueOrDefault());
                if (candididato == null)
                {
                    return NotFound();
                }

                return View(candididato);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Candidato candidato)
        {
            if (ModelState.IsValid)
            {
                string rutaRaiz = _webHostEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;

                if (archivos.Count > 0)
                {
                    var rutaImagenes = Path.Combine(rutaRaiz, @"imagenes\candidatos");

                    string nombreArchivo = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(archivos[0].FileName);

                    // Borra la imagen, si existe alguna
                    if (!string.IsNullOrEmpty(candidato.FotoUrl))
                    {
                        var imagen = Path.Combine(rutaRaiz, candidato.FotoUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagen))
                        {
                            System.IO.File.Delete(imagen);
                        }
                    }

                    if (!Directory.Exists(rutaImagenes))
                    {
                        Directory.CreateDirectory(rutaImagenes);
                    }

                    // Carga el archivo en el servidor
                    using (var stream = new FileStream(Path.Combine(rutaImagenes, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(stream);
                    }

                    candidato.FotoUrl = Path.Combine(@"\imagenes\candidatos", nombreArchivo + extension);
                }
                if (candidato.IdCandidato != 0)
                {
                    _controlador.Candidato.Actualizar(candidato);
                }
                else
                {
                    _controlador.Candidato.Agregar(candidato);
                }
                _controlador.Guardar();
                return RedirectToAction(nameof(Index));
            }

            return View(candidato);
        }

        #region Api Methods

        [HttpDelete]
        public IActionResult Borrar(int id)
        {
            var categoria = _controlador.Candidato.Buscar(id);

            if (categoria == null)
            {
                return Json(new { success = false, message = "Se ha producido un error mientras se borraba." });
            }

            _controlador.Candidato.Remover(categoria);
            _controlador.Guardar();

            return Json(new { success = true, message = "El registro se ha borrado permanentemente." });
        }

        [HttpGet]
        public IActionResult Listar()
        {
            return Json(new { data = _controlador.Candidato.Listar() });
        }

        #endregion
    }
}

WebVotingSystem/Views/Candidatos/Index.cshtml
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Gestión de candidatos</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-area="" asp-controller="Candidatos" asp-action="Upsert" class="btn btn-primary"><i class="fas fa-plus"></i> &nbsp; Crear nuevo candidato</a>
    </div>
</div>

<br />
<div class="p-4 border rounded">
    <table id="tblCandidatos" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th>Nombre</th>
                <th>Partido</th>
                <th>Url de imagen</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts
{
    <script src="~/js/candidatos.js"></script>
}

WebVotingSystem/Views/Candidatos/Upsert.cshtml
@model WebVotingSystem.Models.Candidato

@{
    var titulo = "Crear nuevo candidato";
}

<form method="post" enctype="multipart/form-data">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @if (Model.IdCandidato != 0)
        {
            titulo = "Editar candidato";
            <input type="hidden" asp-for="IdCandidato" />
        }

        <div class="col-12 border-bottom">
            <h2 class="text-primary">@titulo</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Nombre"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div style="display: none;">
                <input asp-for="FotoUrl" class="form-control" value="0" />
            </div>
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Partido"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Partido" class="form-control" />
                    <span asp-validation-for="Partido" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    Imagen
                </div>
                <div class="col-8">
                    @* CONTROL PARA CARGAR ARCHIVO *@
                    <div class="form-group row">
                        <div class="col-4">
                            Imagen
                        </div>
                        <div class="col-8">
                            <input type="file" id="cargar" name="archivos" multiple class="form-control" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    @if (Model.IdCandidato != 0)
                    {
                        <partial name="~/Views/Shared/_BotonesGuardarRegresar.cshtml" model="Model.IdCandidato" />
                    }
                    else
                    {
                        <div class="row">
                            <div class="col">
                                <button type="submit" onclick="return ValidarImagen();" class="btn btn-primary form-control">Crear</button>
                            </div>
                            <div class="col">
                                <a asp-action="Index" class="btn btn-success form-control">Regresar</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        @if (Model.IdCandidato != 0)
        {
            <div class="col-3 offset-1">
                <img src="@Model.FotoUrl" width="100%" style="border-radius:5px; border:1px solid #bbb9b9;" />
            </div>
        }
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>

        function ValidarImagen() {
        }

    </script>
}